version: '3.7'
services:
  tarantool_api:
    image: tarantool_api
    depends_on:
      tarantool:
        condition: service_healthy
    env_file:
      - ../.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: "on-failure"
    networks:
      - tarantool-net

  tarantool:
    image: tarantool/tarantool
    env_file:
      - ../.env
    volumes:
      - ../init:/opt/tarantool
    command: ['tarantool', '/opt/tarantool/init.lua']
    networks:
      - tarantool-net
    restart: "on-failure"

volumes:
  tarantool-data:

networks:
  tarantool-net:
    driver: bridge
    name: tarantool-net
