version: '3.7'
services:

  tarantool_api:
    image: banner_app
    depends_on:
      tarantool:
        condition: service_healthy
    env_file:
      - ../.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: "on-failure"
    networks:
      - tarantool-net

  tarantool:
    image: tarantool/tarantool
    env_file:
      - ../.env
    networks:
      - banner-net
    restart: "on-failure"

volumes:
  tarantool-data:

networks:
  banner-net:
    driver: bridge
    name: tarantool-net
